# Generated by Django 2.2.1 on 2019-07-31 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_portfolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
